### ISSUE TITLE
Add meta tags

### ISSUE THREAD

**Issue by jlegrone** [L4GG/timeline#27]
- Make sure shares on twitter/facebook/google previews look good
- Add tags for mobile (touch icons, theme-color, etc)

**Comment by thekevinscott** [comment]
For reference, current implementation for Twitter and Facebook:

Twitter (Homepage + Event)
<img width="586" alt="screenshot 2017-05-10 21 29 16" src="https://cloud.githubusercontent.com/assets/151596/25927967/90cbc12e-35c7-11e7-99a8-6f891bf6af13.png">

Facebook Messenger (Homepage + Event)
<img width="257" alt="screenshot 2017-05-10 21 26 08" src="https://cloud.githubusercontent.com/assets/151596/25927983/9e1c3570-35c7-11e7-8f6b-771780a9db8a.png">

Facebook Homepage (Homepage + Event)
<img width="511" alt="screenshot 2017-05-10 21 25 35" src="https://cloud.githubusercontent.com/assets/151596/25927993/a59af0de-35c7-11e7-9b7f-38765af4cb5f.png">
<img width="510" alt="screenshot 2017-05-10 21 25 38" src="https://cloud.githubusercontent.com/assets/151596/25927992/a59ae0f8-35c7-11e7-9948-0e1cdea6f342.png">

**Comment by thekevinscott** [comment]
My understanding of how `<meta>` tags work on Facebook (and, presumably Twitter) are that the crawler hits a static page but doesn't process Javascript. So, the `<meta>` tags need to be present at render time, which won't work for this app (I'm *just* getting up to speed so please correct me if I'm wrong).

So I see two choices:

1 - Provide tags for Twitter and Facebook for the site itself, and don't support event-specific tags
2 - Use a service like [prerender.io](https://prerender.io) (they're the first one I found) to prerender the pages, generate the meta tags on the fly, and serve that to the crawlers.

#2 has the benefit of allowing richer sharing of specific events which would be great, but we may run into pricing issues since we're definitely over the limit on prerender. Other thoughts?

**Comment by sgeofrank** [comment]
@thekevinscott I think we'll be fine if their in the index.ejs. I have a pr for them #47

**Comment by sgeofrank** [comment]
Resolved with most recent deploy
