### ISSUE TITLE
Tests complaining about HTTP 403 statuses from nytimes.com

### ISSUE THREAD

**Issue by anseljh** [L4GG/timeline#52]
See, for example this test run, which is otherwise good:
https://travis-ci.org/L4GG/timeline/builds/231283636?utm_source=github_status&utm_medium=notification

25 instances of `Uncaught AssertionError: expected 403 to equal 200`, all related to `nytimes.com` links. I spot checked a few and they were all fine from my browser. Looks like TravisCI is blocked, or something.

One suggestion was to archive these with perma.cc or something similar, and use the archive links. #19 is related to that.

**Comment by jlegrone** [comment]
I started adding archive.org links for some other links that were failing; that's a good solution.  I'm pretty sure travis starts hitting the NY Times paywall after a certain number of requests, and timeline viewers will too if they view enough source links so I'd prefer to use archive links rather than remove the test.
